<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>1.0.5</Version>
    <Authors>Nova4Me2</Authors>
    <Product>Nova4Me2 Drive Recovery</Product>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
</Project>
